### PR TITLE
Implement the interfaces for Hierarchical and SymmetryGroup

### PR DESCRIPTION
**Pull request by lafita**
I came up with a method called _calcGenerators()_ in **RotationGroup** that is able to extract the generators and the operatorFactors at the same time from the permutations of the List of **Rotations** of Peter. I changed the way operatorFactors are stored (because it is redundant the order of generators, compensating by the number), I leave an explanation in the office's whiteboard if you want to check it tomorrow.

With that, we have all we need for our interface. I still have work to do with the **HierarchicalSymmetryGroup** in CeSymm, but I wanted to merge the changes so that you can have a look.

Have a nice holidays!

### CODE REVIEW

**Comment by sbliven** [comment]
I think this is wrong. As a counterexample, consider the tetrahedral group. Here is the table

| I | 0123 |
| :-- | --- |
| A | 1203 |
| AA | 2013 |
| B | 0132 |
| AB | 0312 |
| AAB | 3102 |
| BA | 2130 |
| ABA | 1320 |
| AABA | 3210 |
| BAB | 3021 |
| BAA | 0231 |
| ABAA | 2301 |

Just from the fact that there are 12 elements shows that they can't all be expressed as A^{0,1,2}*B^{0,1}, since that would only explain at most 6 operators.

It should work find for C and D cases right now, but I think we do need to store the factors in order.

**Comment by sbliven** [comment]
BTW, I generated the factors above by finding the shortest path from the identity through the graph of group elements:
tetra
where blue edges are from applying A and grey edges apply B.

**Comment by lafita** [comment]
Yes, that is actually true! I was completely wrong. I guess what I found was only a particular case for D symmetry. The graph is very nice, I will re-implement the method as a graph-searching algorithm to account for all the generator possibilities.

Thank you Spencer!

**Comment by sbliven** [comment]
Sounds good. You shouldn't need to actually create such a graph–just applying the operators to each known element, as done in complete(), should be more-or-less equivalent to a breadth-first search.

**Comment by sbliven** [comment]
Was this already merged into rcsb:master, or does it need more work? Either way it can be closed here I think.

**Comment by lafita** [comment]
It needs more work, so it was not merged.

**Pull request closed without merging**
